[package]
name = "dataScience_polaRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.34.2", features = ["lazy"] }
anyhow = "1.0.75"
rayon = "1.8.0"
